name: SunGather
version: "0.3.9"
slug: modbus_inverter
description: Extract Sungrow data from local Inverter
url: "https://github.com/bohdan-s/SunGather"
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
webui: http://[HOST]:[PORT:8080]/
services:
  - "mqtt:need"
ports:
  8080/tcp: 8080
options: 
  host: 192.168.1.100
  timeout: 10
  scan_interval: 30
  connection: 'modbus'
  smart_meter: True
  use_local_time: False
  log_console: 'INFO'
  log_file: 'OFF'
  level: 'STANDARD'
schema:
  host: str
  timeout: int(3,60)?
  scan_interval: int(5,600)?
  connection: "list(sungrow|modbus|HTTP)"
  smart_meter: bool?
  use_local_time: bool?
  log_console: "list(OFF|INFO|WARNING|ERROR|DEBUG)"?
  log_file: "list(OFF|INFO|WARNING|ERROR|DEBUG)"?
  level: "list(BASIC|STANDARD|DETAIL|ALL)"?